
library(tidyverse)
library(sf)
#library(inborutils)
library(rio)
library(tidyverse)
library(janitor)
library(readxl)
library(openxlsx) 
library(rio)
library(readr)
library(sampling)
library(misty)
library(haven)
library(labelled)
library(stringi)

print("Se han leido las librerias")
